#ifndef DEBUG_VIEW_IDS_GLSL
#define DEBUG_VIEW_IDS_GLSL

// Debug view IDs are grouped by the pipeline data they expose. Keep the
// numeric ranges stable so the shader option remains readable in Iris.

// Final lighting decomposition.
#define DEBUG_VIEW_OUTPUT_COMPOSITE 0
#define DEBUG_VIEW_OUTPUT_DIFFUSE_LIGHTING 1
#define DEBUG_VIEW_OUTPUT_SPECULAR_LIGHTING 2
#define DEBUG_VIEW_OUTPUT_REFRACTION_LIGHTING 3
#define DEBUG_VIEW_OUTPUT_DIFFUSE_IRRADIANCE 4
#define DEBUG_VIEW_OUTPUT_PRIMARY_SURFACE_LIGHT 5
#define DEBUG_VIEW_OUTPUT_MEDIUM_EMISSION 6
#define DEBUG_VIEW_OUTPUT_ABSORPTION_TRANSMITTANCE 7

// Primary material and geometry.
#define DEBUG_VIEW_MATERIAL_SHADING_NORMAL 10
#define DEBUG_VIEW_MATERIAL_DIFFUSE_ALBEDO 11
#define DEBUG_VIEW_MATERIAL_SPECULAR_ALBEDO 12
#define DEBUG_VIEW_MATERIAL_GGX_ALPHA 13

// Diffuse denoiser.
#define DEBUG_VIEW_DIFFUSE_TEMPORAL_HISTORY_SIGNAL 20
#define DEBUG_VIEW_DIFFUSE_FINAL_NORMALIZED_FIRST_MOMENT 21
#define DEBUG_VIEW_DIFFUSE_KISH_EFFECTIVE_SAMPLES 22
#define DEBUG_VIEW_DIFFUSE_NOISE_ONLY_CURRENT_WEIGHT 23
#define DEBUG_VIEW_DIFFUSE_PREPARED_MONTE_CARLO_VARIANCE 24
#define DEBUG_VIEW_DIFFUSE_FILTERED_MONTE_CARLO_VARIANCE 25

// Specular denoiser.
#define DEBUG_VIEW_SPECULAR_SAMPLED_DIRECTION 30
#define DEBUG_VIEW_SPECULAR_CURRENT_TRACKING_HIT_DISTANCE 31
#define DEBUG_VIEW_SPECULAR_TEMPORAL_HISTORY_SIGNAL 32
#define DEBUG_VIEW_SPECULAR_FINAL_VIRTUAL_NORMAL 33
#define DEBUG_VIEW_SPECULAR_KISH_EFFECTIVE_SAMPLES 34
#define DEBUG_VIEW_SPECULAR_RESOLVED_HISTORY_CONTRIBUTION 35
#define DEBUG_VIEW_SPECULAR_NOISE_ONLY_CURRENT_WEIGHT 36
#define DEBUG_VIEW_SPECULAR_PREPARED_MONTE_CARLO_VARIANCE 37
#define DEBUG_VIEW_SPECULAR_FILTERED_MONTE_CARLO_VARIANCE 38

// Refraction and PSR.
#define DEBUG_VIEW_REFRACTION_PSR_ROUTE 40
#define DEBUG_VIEW_REFRACTION_VIRTUAL_ENDPOINT_DISTANCE 41

// Path guiding and radiance cache.
#define DEBUG_VIEW_PATH_GUIDE_FINAL_DIRECTION 50
#define DEBUG_VIEW_RADIANCE_CACHE_SURFACE_HISTORY_SAMPLE 51
#define DEBUG_VIEW_RADIANCE_CACHE_CURRENT_IRRADIANCE 52
#define DEBUG_VIEW_RADIANCE_CACHE_HISTORY_IRRADIANCE 53
#define DEBUG_VIEW_RADIANCE_CACHE_HISTORY_SAMPLE_COUNT 54
#define DEBUG_VIEW_RADIANCE_CACHE_FILTERED_IRRADIANCE 55

// Entity and screen-space motion.
#define DEBUG_VIEW_MOTION_MATCH_STATUS 60
#define DEBUG_VIEW_MOTION_ENTITY_WORLD 61
#define DEBUG_VIEW_MOTION_PRIMARY_SCREEN 62

#endif
