#define DENOISER_SPATIAL_PHI_LUMINANCE MAXENT_SPATIAL_SPECULAR_LIGHT_FIELD_SENSITIVITY
#define MAXENT_ATROUS_SMALL_KERNEL
#define MAXENT_ATROUS_STEP 1
#define MAXENT_ATROUS_DEBUG_VIEW 26
#include "/post/maxent_atrous.glsl"
