#define DENOISER_SPATIAL_PHI_LUMINANCE MAXENT_SPATIAL_SPECULAR_LIGHT_FIELD_SENSITIVITY
#define DENOISER_SPATIAL_REQUIRE_MATERIAL_MATCH 1
#define MAXENT_ATROUS_STEP 8
#define MAXENT_ATROUS_DEBUG_VIEW 29
#include "/post/maxent_atrous.glsl"
